In [1]:
import pandas as pd
import numpy as np
from ast import literal_eval
import os
os.chdir('/Users/samanthamoon/Desktop/DSAN 5000/dsan-5000-project-samjmoon/dsan-website/5000-website/data-cleaning')

metadata_df = pd.read_csv('movies_metadata.csv')
metadata_df['genres'] = metadata_df['genres'].apply(lambda x: [genre['name'] for genre in literal_eval(x)] if isinstance(x, str) else [])
metadata_df.head()

/var/folders/mm/79b3ggcn52x9kcrnqfx5mtk40000gn/T/ipykernel_3332/897346492.py:7: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  metadata_df = pd.read_csv('movies_metadata.csv')

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[Animation, Comedy, Family]",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[Adventure, Fantasy, Family]",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[Romance, Comedy]",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[Comedy, Drama, Romance]",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,[Comedy],NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [2]:
num_columns = metadata_df.shape[1]
num_columns
column_names = metadata_df.columns.tolist()
print("Column names:", column_names)
num_rows = metadata_df.shape[0]
num_rows

Column names: ['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id', 'imdb_id', 'original_language', 'original_title', 'overview', 'popularity', 'poster_path', 'production_companies', 'production_countries', 'release_date', 'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title', 'video', 'vote_average', 'vote_count']

45466

In [3]:
columns_to_drop = ['adult','belongs_to_collection','homepage', 'overview', 'poster_path', 'tagline', 'video', 'status', 'production_countries', 'original_language', 'spoken_languages', 'production_companies']
metadata_df = metadata_df.drop(columns=columns_to_drop, axis=1)
metadata_df.head()
metadata_df = metadata_df.rename(columns={'id': 'tmdbId'})
metadata_df['tmdbId'] = pd.to_numeric(metadata_df['tmdbId'], errors='coerce')
metadata_df['tmdbId'] = metadata_df['tmdbId'].astype(float)
#Check if any column in the DataFrame contains NaN values
any_nan_values = metadata_df.isna().any()

#Display which columns have NaN values
print(any_nan_values)

budget            False
genres            False
tmdbId             True
imdb_id            True
original_title    False
popularity         True
release_date       True
revenue            True
runtime            True
title              True
vote_average       True
vote_count         True
dtype: bool

In [4]:
metadata_df = metadata_df.dropna(subset=['tmdbId', 'imdb_id', 'vote_average', 'vote_count', 'runtime'])
num_rows = metadata_df.shape[0]
num_rows
any_nan_values = metadata_df.isna().any()

# Display which columns have NaN values
print(any_nan_values)
metadata_df.head()

budget            False
genres            False
tmdbId            False
imdb_id           False
original_title    False
popularity        False
release_date       True
revenue           False
runtime           False
title             False
vote_average      False
vote_count        False
dtype: bool

,budget,genres,tmdbId,imdb_id,original_title,popularity,release_date,revenue,runtime,title,vote_average,vote_count
0,30000000,"[Animation, Comedy, Family]",862.0,tt0114709,Toy Story,21.946943,1995-10-30,373554033.0,81.0,Toy Story,7.7,5415.0
1,65000000,"[Adventure, Fantasy, Family]",8844.0,tt0113497,Jumanji,17.015539,1995-12-15,262797249.0,104.0,Jumanji,6.9,2413.0
2,0,"[Romance, Comedy]",15602.0,tt0113228,Grumpier Old Men,11.7129,1995-12-22,0.0,101.0,Grumpier Old Men,6.5,92.0
3,16000000,"[Comedy, Drama, Romance]",31357.0,tt0114885,Waiting to Exhale,3.859495,1995-12-22,81452156.0,127.0,Waiting to Exhale,6.1,34.0
4,0,[Comedy],11862.0,tt0113041,Father of the Bride Part II,8.387519,1995-02-10,76578911.0,106.0,Father of the Bride Part II,5.7,173.0

In [5]:
file_path = './cleaned_metadata_movies.csv' 
metadata_df.to_csv(file_path, index=False)